### ISSUE TITLE
Double notifications

### ISSUE THREAD

**Issue by rappazzo** [valentinfrlch/ha-llmvision#138]
I'd like to discuss the double notifications.  

I could easily make a pull request to change things, but I wanted to understand the reasoning behind it, and discuss the right way to implement.

The conditions on both of the notifications is the same: `"{{ image != '' or video != '' }}"`, but I could see removing the first notification, and making the second notification step conditional on whether or not the ai response is present.  Of course, maybe it is desirable to get the initial notification, and then the ai response separately, since the later could be delayed.  

Are there any thoughts on the best approach here?

**Comment by valentinfrlch** [comment]
The reason there are "two" notifications is simple: The first notification is sent immediately so that users don't miss important events as the summary will add about 5 seconds of delay. I say "two" because the user wont see two separate notifications. Or at least that's how it should be. The second notification should update/replace the first one as seen in the gif in the readme. Are you getting double notifications (as in two separate notifications)?

**Comment by rappazzo** [comment]
I think my frigate must send a slew of notifications at once, so I think that some of them we just not updated.  But I definitely have observed a single notification turn into the updated one, now that I am looking for it.

**Comment by sorenbache** [comment]
> Are you getting double notifications (as in two separate notifications)?

Yes, on my iPhone I get a notification with two beeps (if I have sound on) and buzzing both times. It is - though - updating the same notification. So that part works.
