### ISSUE TITLE
Using it on Node-Red call service.

### ISSUE THREAD

**Issue by alexandrechoske** [valentinfrlch/ha-llmvision#59]
Hi guys, im attempting to use it with Node-Red as well.

HA automations is 100% fine, but on NR is kinda confusing.

![image](https://github.com/user-attachments/assets/3177e391-9b85-4598-b787-402dcdd9e241)

No matter wich types of options I configure, I get this error msg.

I dont know if the JSON is correctly formatted, since NR example is like this.

**Comment by alexandrechoske** [comment]
![image](https://github.com/user-attachments/assets/c8887efa-40cf-4448-aaee-c81d29bf974e)


This is the "example" JSON NR supplies, I only removed the URL and changed the entity.

Same error as well

**Comment by valentinfrlch** [comment]
The problem here is that image_entity expects a list but is given a string, which it then interprets as a list (each character as an item). This is why it says "c" (first letter in "camera.garagem") is not an entity. 
I have no experience with Node Red but since it takes json, I think it should look like this:

```json
"image_entity": ["camera.garagem"]
```

**Comment by alexandrechoske** [comment]
it worked!
thanks!!
