### ISSUE TITLE
Cannot re-add Ollama entry without restarting HA

### ISSUE THREAD

**Issue by nomonkeynodeal** [valentinfrlch/ha-llmvision#69]
First, this is an excellent HA integration. I only found it a day ago after I realized such a thing is possible and specifically searched for it.

Small issue: I removed the Ollama entry in Integrations and when I tried to re-add it, it said an Ollama entry already exists. The problem went away after restarting HA.

I wonder why it is not possible to add more than one Ollama entry. I added another Ollama docker so I can run two different models (two different IPs) simultaneously. I'm using the other one for other things, so I don't need it to work. Just something to think about.

**Comment by valentinfrlch** [comment]
Thanks!
Right now, the deleted configuration is only removed on restart. I'm working on a method to properly remove deleted configs without restarting for the next release.

Supporting multiple configs for one provider should be possible, but I will need to rewrite the way llmvision stores its configuration. So wont be in the next release but I will work on this soon!

**Comment by valentinfrlch** [comment]
In `v1.2.0` there can now be multiple configurations for the same provider. A restart is also no longer necessary when removing configurations. 
`v1.2.0-beta.5` is out now, if you have some time to test it and provide feedback that would be much appreciated. 

- Keep in mind that all providers need to be set up again because the way configs are stored had to be completely rewritten and is incompatible with the old version
- The `provider` input will now also take the id of a configuration instead of the name of the provider. In the UI there is a simple dropdown, but if you have any scripts or automations they will likely stop working (until you fix the provider).

Here is the full changelog: https://github.com/valentinfrlch/ha-llmvision/releases/tag/v1.2.0-beta.5

**Comment by valentinfrlch** [comment]
This issue is now resolved in v1.2.0.
