### ISSUE TITLE
Where is the Blueprint?

### ISSUE THREAD

**Issue by sshaikh** [valentinfrlch/ha-llmvision#82]
### Bug Description
The docs and repo suggest that a blueprint should be available to use, with no mention of extra steps needed to install one. I have llmvision installed but I can't seem to find the blueprint in the list of blueprints.

**Version**: 1.3.0

### Service Call
NA

### Additional context
I have had the integration installed since it was called GPTvision and only supported 3-4 providers (can't remember the exact version I'm afraid!). It has generally updated fine.

**Comment by sshaikh** [comment]
I have tracked this down: https://community.home-assistant.io/t/camera-frigate-intelligent-ai-powered-notifications/785335

Is the expectation to import this manually?

**Comment by valentinfrlch** [comment]
The blueprint is well documented in the examples section of the wiki. You can find it here: https://llm-vision.gitbook.io/examples/examples/automations

Users should be given the choice whether they want to import the blueprint or not as it is not an essential part of the LLM Vision. It is good practice for integrations to not download files into a users filesystem. 
I will add the 'import blueprint' button to the README soon.

**Comment by sshaikh** [comment]
I'm sure I'm missing something, or perhaps not explaining myself properly, but how would someone reading this page know where to import the blueprint from? I use and write blueprints all the time and still was a bit confused :D.

A button would work, but even a paragraph explaining what URL to import would suffice?

**Comment by valentinfrlch** [comment]
I think this is mostly because the blueprint is about one week old at this point. It is also merely a way to make using the integration more accessible and easy to use. There are other use cases for this integrations as well and I want to keep the README as simple as possible.

I am probably biased because I wrote it and therefore know exactly where to look for, but there is a 'Learn more' link directly below the gif showing the notification in the README. 
There is also an 'Examples' button next to the 'Documentation' button. The examples contain the blueprint and other resources as well. The blueprint has also been posted on the exchange and I have posted a link to the exchange in the community forum.
You can also find the yaml file in this repo as well if you'd rather import it yourself.

**Comment by sshaikh** [comment]
I've figured out our disconnect - the documentation/button I initially expected to see before creating this issue does not appear in (my?) Firefox, but does in Chrome. Not sure why, but when it renders it's exactly what I would have looked for. Thanks!

**Comment by iamjackg** [comment]
Can confirm it does not show up on Firefox -- I was equally confused. I'm not sure what's going on: the network inspector simply shows an `NS_BINDING_ABORTED` error for the svg.

**Comment by frostworx** [comment]
I can confirm the "Import blueprint to MYHA button" is visible in google-chrome, but not on firefox 134.0.2 (linux).

Might be a good idea to make this issue or a separate warning sticky and/or reopen the issue.

In any case thank you for this interesting addon! :)

**Comment by valentinfrlch** [comment]
That's weird. The buttons can be created with [this tool](https://my.home-assistant.io/create-link/). Since this seems to be an upstream issue, you may want to create a bug report here: https://github.com/home-assistant/my.home-assistant.io/issues
